name: football
version: 1.0.0
profile: football
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  football:
    staging:
      +materialized: view
    marts:
      +materialized: table
