football:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: football_staging
      location: "{{ env_var('BQ_LOCATION') }}"
      threads: 4